### ISSUE TITLE
Custom Graphs not rendering at all.

### ISSUE THREAD

**Issue by cyberpwnn** [Hidendra/mcstats.org#25] opened 2016-03-31 12:32 UTC
I have created a number of custom graphs, and set it all up. The graphs show up in the admin panel, and after a decent amount of time, the default/normal graphs show up, however the other graphs do not at all. Even adding a custom graph with a return value of 1 statically does literally nothing. You can have a look here for yourself if this project is not already dead. Again.

http://mcstats.org/plugin/React

**Comment by Hidendra** [comment] 2016-03-31 14:15
I've confirmed the graph data is being correctly received by the telemetry backend. I've restarted it and will look again in 15 minutes (next generation) when it should be fixed -- it is likely due to a bug where new graphs are not correctly generated. I'll let you know then.

**Comment by Hidendra** [comment] 2016-03-31 14:39
Your custom graphs are now generating data properly :smile:

**Closed as completed by Hidendra** 2016-03-31 14:39 UTC

**Comment by cyberpwnn** [comment] 2016-04-01 14:01
So I guess its when new graphs are created, they dont generate at all? Because I have new graphs that are not generating (some of them). I have given it over 24 hours, but no change.

Changing one of my pie charts to a line graph is empty, but it says invalid date.
