### ISSUE TITLE
mcstats.org offline - error 500 or ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by Janmm14** [Hidendra/mcstats.org#32] opened 2016-08-08 18:55 UTC

**Comment by fdatoo** [comment] 2016-08-08 19:08
This happens all the time, I hope the issue is resolved soon.

**Comment by nootsponge** [comment] 2016-08-09 14:13
Could it be the host?

**Comment by sgdc3** [comment] 2016-08-09 23:46
#34

**Comment by sgdc3** [comment] 2016-08-13 20:55
@Janmm14 You should close the issue now, the service is online again

**Closed as completed** 2016-08-13 22:36 UTC

**Comment by sgdc3** [comment] 2016-08-13 22:37
@Janmm14 and remember to join the StatsCraft skype group: https://join.skype.com/cc27PEArdQwo
