### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by ethsmith** [Hidendra/mcstats.org#20] opened 2015-10-20 12:26 UTC
The site is down, why? :(

**Comment by Janmm14** [comment] 2015-11-02 11:02
Still down @Hidendra

**Comment by sgdc3** [comment] 2015-11-11 01:20
Still down...

**Comment by sgdc3** [comment] 2015-11-18 22:18
@Hidendra Any news?

**Comment by fdatoo** [comment] 2015-12-09 02:42
@Hidendra We really need this service. Please do not abandon it. If need be, I'll even host it for you. Please, from the bottom of myself and 91 (confirmed) others' hearts, bring it back.

**Comment by ethsmith** [comment] 2015-12-09 03:10
I don't mind hosting it either

**Comment by Janmm14** [comment] 2015-12-24 21:08
@Hidendra Seems like images are online currently, but the normal web frontend is what we want.

**Comment by sgdc3** [comment] 2015-12-25 00:21
The site is online atm ;)

**Comment by fdatoo** [comment] 2015-12-25 03:21
Thank the lord. It's been down for weeks!

**Comment by Janmm14** [comment] 2015-12-25 23:28
great, site currently gives 502 bad gateway @Hidendra

**Comment by sgdc3** [comment] 2015-12-26 00:34
Yeah, offline... (502) :(

**Comment by fdatoo** [comment] 2015-12-26 00:35
Not again!

**Comment by sgdc3** [comment] 2015-12-26 00:55
yeah, and we can't find any official comment/announcement about the issue... :(

**Comment by sgdc3** [comment] 2015-12-26 01:05
My theories:
- bad server infrastructure
- congested sql database
- self-ddossed (too many reports)
- ddossed by an idiot

**Comment by sgdc3** [comment] 2015-12-26 01:05
What do you think guys?

**Comment by fdatoo** [comment] 2015-12-26 02:57
I think I ought to host it myself and just have people point to my web server. Don't know if that's allowed though.

**Comment by fdatoo** [comment] 2015-12-26 02:58
Come to think of it, we could all just make a website for our own plugins and not have to depend on mcstats.org

**Comment by sgdc3** [comment] 2015-12-26 10:50
No, we can create an organization maintained by donations an volunteers. A standard webserver isn't enough to handle the traffic, we need a powerful server with filtered traffic and a good hardware ddos protection.

**Comment by sgdc3** [comment] 2015-12-26 10:51
Anyway, the site is up now. ;)

**Comment by sgdc3** [comment] 2015-12-26 10:56
Just noticed that mcstats is missing a cloudflare protection :/

**Comment by Janmm14** [comment] 2015-12-26 20:50
@sgdc3 There may be issues with promammatic access to mcstats while under cloudflare.

**Comment by sgdc3** [comment] 2015-12-26 21:13
@Janmm14 What do you mean?

**Comment by sgdc3** [comment] 2015-12-26 21:14
I mean cloudflare applied only to the web interface, not the report system.

**Comment by sgdc3** [comment] 2015-12-29 01:26
Offline <_<

**Comment by fdatoo** [comment] 2015-12-31 05:20
Back up. It's a rollercoaster, and still no comment from @Hidendra

**Comment by sgdc3** [comment] 2015-12-31 15:32
yeah

**Comment by sgdc3** [comment] 2016-01-02 13:30
The web interface is online but the database seems to be not. http://mcstats.org/plugin-list/

**Comment by sgdc3** [comment] 2016-01-02 13:32
1,580 requests for second -_-

**Comment by sgdc3** [comment] 2016-01-05 02:37
Aaaaand offline now! -_- (Error 500)

**Comment by Hidendra** [comment] 2016-01-05 03:46
At least for the downtime sporadically happening in the last day or two, 
there was a corrupted value in the Mongo database which was causing it 
to crash when backups were running on it, or if something else reached 
far enough back in the collection to scan over that value.

Looks to be fixed now, although the Mongo index is still being rebuilt, 
so this will take a bit more time before the site is back .... (as of 
this reply it's at 17%, ~1% a minute)

I'll try and throw up a blag post shortly after the reindexing completes 
and everything looks ok. It'll address the occasional downtime that's 
been happening in the last few months as well.

p.s. For Sept -- Dec I quite literally did fall off the face of the 
earth, so I'm finally able to start slowly catching up to things ... :eyes:

p.p.s. only noticing now because of the corrupt fail, but only 142 
million more Mongo documents until 1 billion total documents \o/

**Comment by sgdc3** [comment] 2016-01-05 03:56
Thanks @Hidendra ;)

**Comment by Hidendra** [comment] 2016-01-05 05:04
I'm not really sure what to expect anymore.

2016-01-05T00:03:32.004-0500 I - [initandlisten] Index Build: 885377500/858906291 103%
2016-01-05T00:03:37.776-0500 I - [initandlisten] Index Build: 885712300/858906291 103%
2016-01-05T00:03:40.004-0500 I - [initandlisten] Index Build: 886436400/858906291 103%

**Comment by ethsmith** [comment] 2016-01-05 05:17
lol

**Comment by fdatoo** [comment] 2016-01-05 05:17
@Hidendra Glad you're back though ;)

**Comment by Hidendra** [comment] 2016-01-05 06:11
So it ended up finishing at 108% (932409600/858906291). The thought of ever actually trying to run a query over everything is horrifying

Blog post here http://blog.mcstats.org/index.php/2016/01/05/lets-talk-about-downtime/ I'll have to re-read after I've slept to find out how incoherent I was

@SirFaizdat Thank you.

**Comment by sgdc3** [comment] 2016-01-05 11:34
@TekkitCommando  I think we can close this ;)

**Closed as completed** 2016-01-05 13:09 UTC

**Comment by T0biii** [comment] 2016-08-08 18:03
the site is down :-1:
