### ISSUE TITLE
Offline, again! :(

### ISSUE THREAD

**Issue by sgdc3** [Hidendra/mcstats.org#29] opened 2016-06-13 23:47 UTC
@Hidendra

**Comment by TreyRuffy** [comment] 2016-06-14 04:22
;-;

How long was the last downtime?

**Comment by boomboompower** [comment] 2016-06-15 10:47
@TreyRuffy Duplicate of https://github.com/Hidendra/mcstats.org/issues/20

The website is back up. @sgdc3 Please close this :P

**Comment by sgdc3** [comment] 2016-06-15 12:52
Yeah, online again

**Closed as completed** 2016-06-15 12:51 UTC
